import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'
import { useNetworkInformation } from './networkInformation';
import YoutubeIframe from "./youtubevideo";

export default function Home() {
  const videoProps = {
    videoId: "DgqAAE9Aagc?rel=0&vq=medium",
    title: "The video:",
    autoplay: true
  }

  const [connection, setConnection] = useState(useNetworkInformation().effectiveType);
  //useEffect(() => setConnection(useNetworkInformation().effectiveType), []);

  const networkInformation = useNetworkInformation().effectiveType;
  
  // const networkInformation = useNetworkInformation();
  // console.log("hei"+networkInformation.effectiveType);

  // useEffect(() => {
  //   const networkInformation = useNetworkInformation();
  // });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <a href="https://nextjs.org">video page!</a> */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          APW project<br></br>Fall 2022 v1
        </h1>

        <p className={styles.description}>
          This progressive web app renders content dynamically <br></br> based on your network connection by using the <br></br>
          <a href="https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API">network information API</a>
          {/* <code className={styles.code}>network information API</code> */}
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
              <p>Your current connection:</p>
              <h2 className={styles.centerText}>{networkInformation}</h2>
          </div>
        </div>

        {/* <p className={styles.description}>Your current connection:
        </p>
        {/* <NetworkInfo/> */}
        {/* <h1>{networkInformation}</h1> */}

        
        {/* <div className={styles.videoGrid}>
         </div> */}
        
        <h2>{videoProps.title}</h2>
        <YoutubeIframe {... videoProps} />

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Created by Sindre</p>
      </footer>
    </div>
  )
}
